MVCPublicAPI/Models/DogResponse.cs
namespace MVCPublicAPI.Models
{
    public class DogResponse
    {

        public string Message { get; set; }
        public string Status { get; set; }


    }
}

MVCPublicAPI/Models/DogViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCPublicAPI.Models
{
    public class DogViewModel
    {
        public string ImageURL { get; set; }

    }
}

MVCPublicAPI/Models/ErrorViewModel.cs
using System;

namespace MVCPublicAPI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCPublicAPI/Models/HolidayResponse.cs
namespace MVCPublicAPI.Models
{
    public class HolidayResponse
    {

        public bool holiday { get; set; }
        public string date { get; set; }

    }
}

MVCPublicAPI/Models/HolidayViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCPublicAPI.Models
{
    public class HolidayViewModel
    {
        public string Date { get; set; }
        public bool Holiday { get; set; }
    }
}

MVCPublicAPI/Models/Planets.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCPublicAPI.Models
{
    public class Planets
    {
        public string Name { get; set; }
        public string Url { get; set; }

    }
}

MVCPublicAPI/Models/StarwarsResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCPublicAPI.Models
{
    public class StarwarsResponse
    {
        //public int Id { get; set; }
        //public string Name { get; set; }
        //public string LinktoURL { get; set; }
        //public string PlanetNumber { get; set; }
        //public IEnumerable<Planets> Planets { get; set; }

        public int Count { get; set; }
        public string Next { get; set; }
        public object Previous { get; set; }
        public IEnumerable<PlanetResponse> Results { get; set; }

    }


    public class PlanetResponse
    {
        public string Name { get; set; }
        public string Rotation_period { get; set; }
        public string Orbital_period { get; set; }
        public string Diameter { get; set; }
        public string Climate { get; set; }
        public string Gravity { get; set; }
        public string Terrain { get; set; }
        public string Surface_water { get; set; }
        public string Population { get; set; }
        public string[] Residents { get; set; }
        public string[] films { get; set; }
        public DateTime Created { get; set; }
        public DateTime Edited { get; set; }
        public string Url { get; set; }
    }

}

MVCPublicAPI/Models/StarwarsViewModel.cs
using System.Collections.Generic;

namespace MVCPublicAPI.Models
{
    public class StarwarsViewModel
    {
        //public int Id { get; set; }
        //public string Name { get; set; }
        //public string LinktoURL { get; set; }

        //public string PlanetNumber { get; set; }
        //public string Name { get; set; }
        public IList<Planet> Planets { get; set; }
        public List<Planet> Planet { get; set; }
        public string UserSelectedPlanet { get; set; }

    }

    public class Planet
    {
        public string Url { get; set; }
        public string Name { get; set; }
    }

}

MVCPublicAPI/Controllers/DogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCPublicAPI.Models;
using MVCPublicAPI.Services;

namespace MVCPublicAPI.Controllers
{
    public class DogController : Controller
    {
        private IDogService _dogService;
        private IDogFacade _dogFacade;

        public DogController(IDogFacade dogFacade)
        {
            _dogFacade = dogFacade;
        }

        public async Task<IActionResult> Dog()
        {
            var viewModel = new DogViewModel();
            var result = await _dogFacade.GetDogViewModel();
            return View(result);
        }
    }
}

MVCPublicAPI/Controllers/HolidayController.cs
using Microsoft.AspNetCore.Mvc;
using MVCPublicAPI.Models;
using MVCPublicAPI.Services;
using System.Threading.Tasks;

namespace MVCPublicAPI.Controllers
{
    public class HolidayController : Controller
    {
        private IHolidayService _holidayService;
        private IHolidayFacade _holidayFacade;

        public HolidayController(IHolidayFacade holidayFacade)
        {
            _holidayFacade = holidayFacade;
        }

        public IActionResult HolidayFormView()
        {
            return View();
        }


        public async Task<IActionResult> Holiday(HolidayViewModel model)
        {
            // var viewModel = new HolidayViewModel();
            var result = await _holidayFacade.GetHolidayViewModel(model.Date);
            return View(result);
        }
    }
}

MVCPublicAPI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCPublicAPI.Models;

namespace MVCPublicAPI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCPublicAPI/Controllers/StarwarsController.cs
using Microsoft.AspNetCore.Mvc;
using MVCPublicAPI.Models;
using MVCPublicAPI.Services;
using System.Threading.Tasks;

namespace MVCPublicAPI.Controllers
{
    public class StarwarsController : Controller
    {
        //private IStarwarsService _starwarsService;
        private IPlanetService _planetService;
        private IStarwarsFacade _starwarsFacade;

        public StarwarsController(IStarwarsFacade starwarsFacade, IPlanetService planetService)
        {
            _starwarsFacade = starwarsFacade;
            _planetService = planetService;


        }


        public async Task<IActionResult> StarwarsView()
        {
            var result = await _starwarsFacade.GetAllPlanets();
            return View(result);
        }


        public IActionResult UserPlanetsView(StarwarsViewModel model)
        {

            var result = _planetService.AddNewPlanet(model);
            return View(result);
        }


        public async Task<IActionResult> Index()
        {
            var starships = await _starwarsFacade.GetAllStarships();

            return View(starships);
        }



    }
}

MVCPublicAPI/Views/Dog/Dog.cshtml
@model MVCPublicAPI.Models.DogViewModel

@{
    ViewData["Title"] = "Dog";
}

<h1>Dog</h1>

<div>
    <h4>DogResponse</h4>
    <img src="@Model.ImageURL" />
    <hr />
</div>

MVCPublicAPI/Views/Holiday/Holiday.cshtml
@model MVCPublicAPI.Models.HolidayViewModel

@{
    ViewData["Title"] = "Holiday";
}

<h1>Holiday</h1>

<div>
    <h4>HolidayViewModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Holiday)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Holiday)
        </dd>

    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MVCPublicAPI/Views/Holiday/HolidayFormView.cshtml
@model MVCPublicAPI.Models.HolidayViewModel

@{
    ViewData["Title"] = "HolidayFormView";
}

<h1>HolidayFormView</h1>

<h4>HolidayViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Holiday">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Holiday" /> @Html.DisplayNameFor(model => model.Holiday)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCPublicAPI/Views/Home/Index.cshtml
@*@{
        ViewData["Title"] = "Home Page";
    }

    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>

    @model MVCPublicAPI.Models.HolidayViewModel

    @{
        ViewData["Title"] = "View";
    }

    <h1>View</h1>

    <h4>HolidayViewModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Holiday">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

MVCPublicAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCPublicAPI</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-darkly.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCPublicAPI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Starwars" asp-action="Index">Starships</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dog" asp-action="Dog">Dog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Holiday" asp-action="Holiday">Holiday</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Holiday" asp-action="HolidayFormView">HolidayForm</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Starwars" asp-action="StarwarsView">Starwars Fan Page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MVCPublicAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

MVCPublicAPI/Views/Starwars/Index.cshtml
@model MVCPublicAPI.DAL.StarshipDALModel


@foreach (var starship in Model.Starship)
{

    <p>@starship.Name    </p>


}

MVCPublicAPI/Views/Starwars/StarwarsView.cshtml
@model MVCPublicAPI.Models.StarwarsViewModel

@{
    ViewData["Title"] = "StarwarsView";
}

    @*<style>
        body {
                                      color: whitesmoke;

            background-image: url("http://getwallpapers.com/wallpaper/full/d/7/7/92778.jpg#.XdFnrU-RO9o.link");
              background-size: auto;

        }
    </style>*@

<h1>Starwars</h1>

<div class="dropdown">
    <form asp-controller="Starwars" asp-action="UserPlanetsView">
        <div class="form-group">
            <select asp-for="@Model.UserSelectedPlanet">

                @foreach (var item in Model.Planets)
                {
                    <option value="@item.Name">@item.Name</option>
                }
            </select>
            <input type="submit" value="Submit" class="btn btn-primary" />

        </div>
    </form>
</div> 

MVCPublicAPI/Views/Starwars/UserPlanetsView.cshtml
@model MVCPublicAPI.Models.StarwarsViewModel
@{
    ViewData["Title"] = "StarwarsFormView";
}
    @*<style>
        body {
             color: whitesmoke;
            background-image: url("http://getwallpapers.com/wallpaper/full/d/7/7/92778.jpg#.XdFnrU-RO9o.link");
              background-size: auto;
        }
    </style>*@

    <h1>
        @Html.DisplayNameFor(model => model.UserSelectedPlanet)
    </h1>


<div>
    <h4>Your Favorite Planets</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserSelectedPlanet)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserSelectedPlanet)
        </dd>
    </dl>
</div>